const item = [

    {
        id: '001',
        item_image: 'images/products/1.jpg',
        stars: 4.5,
        no_of_reviews: 1400,
        company_name: 'Carlton London',
        item_name: 'Rhodium_Plated CZ Floral Studs',
        current_price: 500,
        original_price:1045,
        discount_percentage:45,
        return_period: 14,
        delivery_date: '10 Oct 2023',
    },

    {
        id: '002',
        item_image: 'images/products/2.jpg',
        stars: 4.3,
        no_of_reviews: 1400,
        company_name: 'CUKOO',
        item_name: 'Women Padded Halter Neck Swimming Dress',
        current_price: 1507,
        original_price:2599,
        discount_percentage:42,
        return_period: 14,
        delivery_date: '10 Oct 2023',
    },

    {
        id: '003',
        item_image: 'images/products/3.jpg',
        stars: 4.1,
        no_of_reviews: 1400,
        company_name: 'NUEVOSDAMAS',
        item_name: 'Women Red & White Printed A-Line Knee-Length Skirts',
        current_price: 495,
        original_price:1599,
        discount_percentage:69,
        return_period: 14,
        delivery_date: '10 Oct 2023',
    },

    {
        id: '004',
        item_image: 'images/products/4.jpg',
        stars: 5.0,
        no_of_reviews: 1400,
        company_name: 'ADIDAS',
        item_name: 'Indian Cricket ODI Jersey',
        current_price: 999,
        original_price:999,
        discount_percentage:0,
        return_period: 14,
        delivery_date: '10 Oct 2023',
    },

    {
        id: '005',
        item_image: 'images/products/5.jpg',
        stars: 4.2,
        no_of_reviews: 1400,
        company_name: 'Roadster',
        item_name: 'Pure Cotton T-shirt',
        current_price: 489,
        original_price:1399,
        discount_percentage:65,
        return_period: 14,
        delivery_date: '10 Oct 2023',
    },

    {
        id: '006',
        item_image: 'images/products/6.jpg',
        stars: 0.0,
        no_of_reviews: 1400,
        company_name: 'Nike',
        item_name: 'Men ReactX Running Shoes',
        current_price: 14995,
        original_price:14995,
        discount_percentage:0,
        return_period: 14,
        delivery_date: '10 Oct 2023',
    },

    {
        id: '007',
        item_image: 'images/products/7.jpg',
        stars: 4.2,
        no_of_reviews: 1400,
        company_name: 'Carlton London',
        item_name: 'The Indian Garage Co',
        current_price: 639,
        original_price:1599,
        discount_percentage:60,
        return_period: 14,
        delivery_date: '10 Oct 2023',
    },

    {
        id: '008',
        item_image: 'images/products/8.jpg',
        stars: 4.2,
        no_of_reviews: 1400,
        company_name: 'Nivea',
        item_name: 'Men Fresh Deodrant 150ml',
        current_price: 142,
        original_price:142,
        discount_percentage:50,
        return_period: 14,
        delivery_date: '10 Oct 2023',
    }

];